# Generated by Django 4.2.6 on 2023-10-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='book_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sinf'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sinf'),
        ),
    ]
