# Generated by Django 4.2.6 on 2023-10-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_body_alter_comment_student_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='javob',
            old_name='comment',
            new_name='com',
        ),
    ]
