# Generated by Django 4.2.6 on 2023-10-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_com_javob_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='javob',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='javob',
            old_name='name',
            new_name='names',
        ),
    ]
