# Generated by Django 4.2.6 on 2023-10-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_comment_javob_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javob',
            name='comments',
            field=models.CharField(max_length=500),
        ),
    ]
