# Generated by Django 4.2.6 on 2023-10-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_javob_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javob',
            name='comments',
            field=models.IntegerField(),
        ),
    ]
