# Generated by Django 4.2.6 on 2023-10-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_javob_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
