# Generated by Django 4.2.6 on 2023-10-08 02:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('book_class', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
