# Generated by Django 4.2.6 on 2023-10-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_books_audio_books_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files_blog',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.files_blog'),
        ),
    ]
